@echo off
setlocal EnableDelayedExpansion
REM install.bat — AuraMCP Server install on Windows.
REM Prompts for an installation directory (default: the directory this script lives in),
REM then creates a Workspace\ subfolder inside it and points AGENT_WORKSPACE there.

echo =========================================
echo  AuraMCP Server - Installation
echo =========================================
echo.

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

set "DEFAULT_INSTALL_DIR=%SCRIPT_DIR%"
set /p "INSTALL_DIR=Install location [%DEFAULT_INSTALL_DIR%]: "
if "%INSTALL_DIR%"=="" set "INSTALL_DIR=%DEFAULT_INSTALL_DIR%"

REM Trim trailing backslash
if "%INSTALL_DIR:~-1%"=="\" set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"

if not exist "%INSTALL_DIR%" (
    echo [INFO] Creating %INSTALL_DIR%
    mkdir "%INSTALL_DIR%"
)

set "INSTALL_BIN_DIR=%INSTALL_DIR%\bin"
set "WORKSPACE_DIR=%INSTALL_DIR%\Workspace"

REM Lay out: installer always operates on its own folder; symlinks back to the
REM project tree are useful when install/launch are different folders.
set "PROJECT_ROOT=%SCRIPT_DIR%"

REM Workspace under the chosen install dir
if not exist "%WORKSPACE_DIR%" mkdir "%WORKSPACE_DIR%"

REM Seed Workspace with the agent templates if missing
if not exist "%WORKSPACE_DIR%\SOUL.md"   copy /y "%PROJECT_ROOT%\SOUL.md"   "%WORKSPACE_DIR%\SOUL.md" > nul
if not exist "%WORKSPACE_DIR%\USER.md"   copy /y "%PROJECT_ROOT%\USER.md"   "%WORKSPACE_DIR%\USER.md" > nul
if not exist "%WORKSPACE_DIR%\MEMORY.md" copy /y "%PROJECT_ROOT%\MEMORY.md" "%WORKSPACE_DIR%\MEMORY.md" > nul
if not exist "%WORKSPACE_DIR%\Wiki"      mkdir "%WORKSPACE_DIR%\Wiki"
if not exist "%WORKSPACE_DIR%\plans"     mkdir "%WORKSPACE_DIR%\plans"
if not exist "%WORKSPACE_DIR%\compacted-sessions" mkdir "%WORKSPACE_DIR%\compacted-sessions"

REM --- Tooling checks ---
node --version > nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js not found. Install from https://nodejs.org/ (LTS recommended^).
    pause
    exit /b 1
)
for /f "tokens=*" %%a in ('node --version') do set NODE_VER=%%a
echo [OK] Node.js found: %NODE_VER%

npm --version > nul 2>&1
if errorlevel 1 (
    echo [ERROR] npm not found.
    pause
    exit /b 1
)
for /f "tokens=*" %%a in ('npm --version') do set NPM_VER=%%a
echo [OK] npm found: %NPM_VER%

python --version > nul 2>&1
if errorlevel 1 (
    echo [WARN] Python not found. The RAG tool requires Python with chromadb.
) else (
    for /f "tokens=*" %%a in ('python --version') do set PY_VER=%%a
    echo [OK] Python found: %PY_VER%
)

REM --- Install dependencies + build ---
echo.
echo [INFO] Installing npm dependencies...
npm install
if errorlevel 1 (
    echo [ERROR] npm install failed.
    pause
    exit /b 1
)
echo [OK] Dependencies installed.

echo.
echo [INFO] Compiling TypeScript...
npm run build
if errorlevel 1 (
    echo [ERROR] Build failed.
    pause
    exit /b 1
)
echo [OK] Build completed.

REM --- Optional embeddings setup ---
echo.
echo [INFO] Downloading llama.cpp + nomic-embed-text-v1.5 GGUF for RAG...
call scripts\install_embeddings.bat
if errorlevel 1 (
    echo [WARN] Embeddings download skipped or failed. You can run scripts\install_embeddings.bat manually later.
)

REM --- Install launcher into chosen bin dir ---
if not exist "%INSTALL_BIN_DIR%" mkdir "%INSTALL_BIN_DIR%"

(
    echo @echo off
    echo setlocal
    echo REM Auto-generated by install.bat.
    echo set "PROJECT_ROOT=%PROJECT_ROOT%"
    echo set "WORKSPACE_DIR=%WORKSPACE_DIR%"
    echo set "AGENT_WORKSPACE=%%WORKSPACE_DIR%%"
    echo cd /d "%%PROJECT_ROOT%%"
    echo node dist\index.js
) > "%INSTALL_BIN_DIR%\auramcp-server.bat"

echo.
echo =========================================
echo  Installation completed!
echo =========================================
echo.
echo   Install dir:  %INSTALL_DIR%
echo   Project root: %PROJECT_ROOT%
echo   Workspace:    %WORKSPACE_DIR%
echo.
echo Launcher written to:
echo   %INSTALL_BIN_DIR%\auramcp-server.bat
echo.
echo Point AnythingLLM / LM Studio at:
echo   command: "%INSTALL_BIN_DIR%\auramcp-server.bat"
echo   or, directly: node "%PROJECT_ROOT%\dist\index.js" with AGENT_WORKSPACE=%WORKSPACE_DIR%
echo.
pause
