#!/usr/bin/env bash
# install.sh — AuraMCP Server install on POSIX (Linux, macOS, WSL).
# Prompts for an installation directory (default: the directory this script lives in),
# then creates a Workspace/ subfolder inside it and points AGENT_WORKSPACE there.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_INSTALL_DIR="${SCRIPT_DIR}"

read -r -p "Install location [${DEFAULT_INSTALL_DIR}]: " INSTALL_DIR
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}"

INSTALL_DIR="$(cd "$(dirname "${INSTALL_DIR}")" 2>/dev/null && cd "$(dirname "${INSTALL_DIR}")" && pwd)/$(basename "${INSTALL_DIR}")" || INSTALL_DIR="${INSTALL_DIR}"

mkdir -p "${INSTALL_DIR}"
INSTALL_BIN_DIR="${INSTALL_DIR}/bin"
WORKSPACE_DIR="${INSTALL_DIR}/Workspace"
PROJECT_ROOT="${SCRIPT_DIR}"

mkdir -p "${WORKSPACE_DIR}"

# Seed the Workspace with the agent templates if missing.
cp -n "${PROJECT_ROOT}/SOUL.md"   "${WORKSPACE_DIR}/SOUL.md"   2>/dev/null || true
cp -n "${PROJECT_ROOT}/USER.md"   "${WORKSPACE_DIR}/USER.md"   2>/dev/null || true
cp -n "${PROJECT_ROOT}/MEMORY.md" "${WORKSPACE_DIR}/MEMORY.md" 2>/dev/null || true
mkdir -p "${WORKSPACE_DIR}/Wiki"
mkdir -p "${WORKSPACE_DIR}/plans"
mkdir -p "${WORKSPACE_DIR}/compacted-sessions"

# --- Tooling checks ---
if ! command -v node &> /dev/null; then
  echo "[ERROR] Node.js not found." >&2
  echo "Install it (Ubuntu/Debian: sudo apt install nodejs npm; macOS: brew install node)." >&2
  exit 1
fi
echo "[OK] Node.js found: $(node --version)"

if ! command -v npm &> /dev/null; then
  echo "[ERROR] npm not found." >&2
  exit 1
fi
echo "[OK] npm found: $(npm --version)"

# RAG is Python-free; only the GGUF model is downloaded by install_embeddings.

# --- Install + build ---
echo
echo "[INFO] Installing npm dependencies..."
npm install

echo
echo "[INFO] Compiling TypeScript..."
npm run build

echo
echo "[INFO] Downloading nomic-embed-text-v2-moe GGUF for RAG (Python-free)..."
bash "${PROJECT_ROOT}/scripts/install_embeddings.sh" || \
  echo "[WARN] Embeddings download skipped or failed. Re-run scripts/install_embeddings.sh manually later."

# --- Install launcher ---
mkdir -p "${INSTALL_BIN_DIR}"

cat > "${INSTALL_BIN_DIR}/auramcp-server" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh.
export PROJECT_ROOT="${PROJECT_ROOT}"
export WORKSPACE_DIR="${WORKSPACE_DIR}"
export AGENT_WORKSPACE="\${WORKSPACE_DIR}"
cd "\${PROJECT_ROOT}"
exec node dist/index.js "\$@"
EOF
chmod +x "${INSTALL_BIN_DIR}/auramcp-server"

echo
echo "========================================="
echo " Installation completed!"
echo "========================================="
echo
echo "  Install dir:  ${INSTALL_DIR}"
echo "  Project root: ${PROJECT_ROOT}"
echo "  Workspace:    ${WORKSPACE_DIR}"
echo
echo "Launcher written to:"
echo "  ${INSTALL_BIN_DIR}/auramcp-server"
echo
echo "Point AnythingLLM / LM Studio at:"
echo "  command: ${INSTALL_BIN_DIR}/auramcp-server"
echo "  or, directly: node ${PROJECT_ROOT}/dist/index.js with AGENT_WORKSPACE=${WORKSPACE_DIR}"
echo
